# Generated by Django 4.1.7 on 2023-03-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('take_me_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='challenge',
            table='challenge',
        ),
    ]
