# Generated by Django 4.1.7 on 2023-03-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('take_me_app', '0002_alter_challenge_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpeningHours',
        ),
    ]
