# Generated by Django 4.1.7 on 2023-03-28 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('take_me_app', '0003_delete_openinghours'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.SmallIntegerField(db_column='day')),
                ('opening_time', models.TimeField(db_column='opening_time')),
                ('closing_time', models.TimeField(db_column='closing_time')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='take_me_app.business')),
            ],
            options={
                'db_table': 'opening_hours',
            },
        ),
    ]
