# Generated by Django 4.1.7 on 2023-05-15 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('take_me_app', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='cover',
            field=models.URLField(blank=True, db_column='cover_url', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.URLField(blank=True, db_column='logo_url', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_google_login',
            field=models.BooleanField(db_column='is_google_login', default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='business_address', to='take_me_app.business'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='user_address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone_num',
            field=models.IntegerField(blank=True, db_column='phone_num', null=True),
        ),
        migrations.AlterField(
            model_name='businessaccessibility',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibilities', to='take_me_app.business'),
        ),
        migrations.AlterField(
            model_name='businesschallengedetails',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_details', to='take_me_app.challenge'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='take_me_app.business'),
        ),
    ]
