# Generated by Django 4.1.7 on 2023-05-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_me_app', '0006_business_cover_business_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_google_login',
            field=models.BooleanField(blank=True, db_column='is_google_login', null=True),
        ),
    ]
