# Generated by Django 4.1.7 on 2023-05-30 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('take_me_app', '0007_alter_userprofile_is_google_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='whotochallenge',
            name='is_read',
            field=models.BooleanField(db_column='is_read', default=False),
        ),
        migrations.AddField(
            model_name='whotochallenge',
            name='who_challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Sender_challenge', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.SmallIntegerField(blank=True, db_column='number', null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, db_column='street', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='whotochallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepts_challenge', to=settings.AUTH_USER_MODEL),
        ),
    ]
