# Generated by Django 4.1.7 on 2023-06-07 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('take_me_app', '0009_alter_whotochallenge_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesschallengedetails',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='whotochallenge',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_challenged', to='take_me_app.challenge'),
        ),
    ]
